# NumPy 
NumPy is a Python library used for working with arrays. 
NumPy stands for Numerical Python.
It also has functions for working in domain of linear algebra, fourier transform, and matrices. 

In [1]:
import numpy as np

In [50]:
a=np.array([23,21,45,46,78]) # one dimentional array with 5 elements
a

array([23, 21, 45, 46, 78])

In [51]:
a.shape # number of elements

(5,)

In [52]:
a=np.array([23,21,45,46,78,34,454,54,56,76,46,86]) # one dimentional array
a

array([ 23,  21,  45,  46,  78,  34, 454,  54,  56,  76,  46,  86])

In [63]:
a.shape  # Array has 12 elements like 12 columns

(1, 12)

In [73]:
a.shape=(4,3) #Reshaping the array elements
a           # create 4 * 3 =12 elements array of 4 rows 3 columns

array([[ 23,  21,  45],
       [ 46,  78,  34],
       [454,  54,  56],
       [ 76,  46,  86]])

In [74]:
a.shape=(3,4) #Reshaping the array elements
a           # create 3 * 4 =12 elements array of 3 rows 4 columns

array([[ 23,  21,  45,  46],
       [ 78,  34, 454,  54],
       [ 56,  76,  46,  86]])

In [64]:
a.shape=(1,12)
a

array([[ 23,  21,  45,  46,  78,  34, 454,  54,  56,  76,  46,  86]])

In [68]:
a.shape=(6,2)  # create 6 * 2 =12 elements  6 rows 2 columns
a

array([[ 23,  21],
       [ 45,  46],
       [ 78,  34],
       [454,  54],
       [ 56,  76],
       [ 46,  86]])

In [70]:
a.shape=(2,6)  # create 2 * 6 =12 elements  2 rows 6 columns
a

array([[ 23,  21,  45,  46,  78,  34],
       [454,  54,  56,  76,  46,  86]])

In [23]:
b=np.array([[21,44,56],[54,34,67],[45,34,56]]) #two dimentional array
b

array([[21, 44, 56],
       [54, 34, 67],
       [45, 34, 56]])

In [55]:
b.shape # Array of 3 rows and 3 cloumns

(3, 3)

In [15]:
c=np.array([2,1,4,6,5,6]).reshape(2,3)
c

array([[2, 1, 4],
       [6, 5, 6]])

In [17]:
b=np.array([[21,44,56],[54,34,67]]) #two dimentional array
b

array([[21, 44, 56],
       [54, 34, 67]])

In [19]:
b=np.array([[21,44,56],[54,34,67],[45,34,56]]) #two dimentional array
b

array([[21, 44, 56],
       [54, 34, 67],
       [45, 34, 56]])

In [46]:
np.zeros(10) # 0 elements 10

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [47]:
np.zeros((4,4)) # Row=4,Column=4  filled with 0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
np.zeros((2,3)) # Row=2,Column=3 filled with 0

array([[0., 0., 0.],
       [0., 0., 0.]])

In [48]:
np.ones(10)  # Array of 10 elements filled with 1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [49]:
np.ones(4) # Array of 4 elements filled with 1

array([1., 1., 1., 1.])

In [39]:
np.ones((3,2))   # Row=3,Column=2

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [40]:
np.ones((2,3))   # Row=2,Column=3

array([[1., 1., 1.],
       [1., 1., 1.]])