# NumPy 
NumPy is a Python library used for working with arrays. 
NumPy stands for Numerical Python.
It also has functions for working in domain of linear algebra, fourier transform, and matrices. 

In [6]:
import numpy as np  # import numpy library to the Jupiter

In [8]:
np.sqrt(25)  # test some functions in numpy library

5.0

In [5]:
np.power(3,2)

9

In [9]:
np.exp(3)

20.085536923187668

In [10]:
np.sin(60)

-0.3048106211022167

In [11]:
np.cos(45)

0.5253219888177297

In [15]:
np.tan(30)

-6.405331196646276

In [16]:
np.log(4)

1.3862943611198906

In [18]:
np.round(10.565)

11.0

In [19]:
np.round(10.465)

10.0

In [22]:
np.pi  # pi value

3.141592653589793

In [25]:
np.e  # eulers value  or 'e' value

2.718281828459045

In [31]:
np.inf  # to use as infinity in python or +ve infinity

inf

In [30]:
np.NINF # -ve infinity

-inf

In [29]:
-np.inf  # can use as -ve infinity also

-inf

In [32]:
import numpy as np

In [33]:
a=np.array([23,21,45,46,78]) # one dimentional array with 5 elements
a

array([23, 21, 45, 46, 78])

In [65]:
[[21,44,56],[54,34,67],[45,34,56]] #i.e lists within lists or  nested lists is a two dimentional array

[[21, 44, 56], [54, 34, 67], [45, 34, 56]]

In [41]:
b=np.array([[21,44,56],[54,34,67],[45,34,56]]) #Two dimentional arrays.. We use nested lists here. i.e lists within lists
b                                              #Two dimentional arrays means it is having rows as well as columns

array([[21, 44, 56],
       [54, 34, 67],
       [45, 34, 56]])

In [42]:
a.shape

(5,)

In [43]:
b.shape

(3, 3)

In [46]:
print(a.shape)   # one dimentional array only shows the count of elements
print(b.shape)   # multi dimention arrays shows row count and column count

(5,)
(3, 3)


In [49]:
print(a.ndim)  # get the number of dimentions as one 
print(b.ndim)  # get the number of dimentions as 2 

1
2


In [50]:
print(a.dtype)  # get the data type
print(b.dtype)  # get the data type

int32
int32


In [54]:
print(a.size)   # get the size of array or the element count of the array
print(b.size)   # get the size of array or the element count of the array

5
9


In [62]:
c=np.array([23,'2',45,46,78]) 

In [63]:
print(c.size) 

5


In [64]:
print(c.dtype) 

<U11


In [66]:
import numpy as np

In [67]:
a=np.array([23,21,45,46,78]) # one dimentional array with 5 elements
a

array([23, 21, 45, 46, 78])

In [68]:
a.shape # number of elements

(5,)

In [69]:
a=np.array([23,21,45,46,78,34,454,54,56,76,46,86]) # one dimentional array
a

array([ 23,  21,  45,  46,  78,  34, 454,  54,  56,  76,  46,  86])

In [70]:
a.shape  # Array has 12 elements like 12 columns

(12,)

In [71]:
a.shape=(4,3) #Reshaping the array elements
a           # create 4 * 3 =12 elements array of 4 rows 3 columns

array([[ 23,  21,  45],
       [ 46,  78,  34],
       [454,  54,  56],
       [ 76,  46,  86]])

In [72]:
a.shape=(3,4) #Reshaping the array elements
a           # create 3 * 4 =12 elements array of 3 rows 4 columns

array([[ 23,  21,  45,  46],
       [ 78,  34, 454,  54],
       [ 56,  76,  46,  86]])

In [73]:
a.shape=(1,12)
a

array([[ 23,  21,  45,  46,  78,  34, 454,  54,  56,  76,  46,  86]])

In [74]:
a.shape=(6,2)  # create 6 * 2 =12 elements  6 rows 2 columns
a

array([[ 23,  21],
       [ 45,  46],
       [ 78,  34],
       [454,  54],
       [ 56,  76],
       [ 46,  86]])

In [75]:
a.shape=(2,6)  # create 2 * 6 =12 elements  2 rows 6 columns
a

array([[ 23,  21,  45,  46,  78,  34],
       [454,  54,  56,  76,  46,  86]])

In [76]:
b=np.array([[21,44,56],[54,34,67],[45,34,56]]) #two dimentional array
b

array([[21, 44, 56],
       [54, 34, 67],
       [45, 34, 56]])

In [77]:
b.shape # Array of 3 rows and 3 cloumns

(3, 3)

In [78]:
c=np.array([2,1,4,6,5,6]).reshape(2,3) # at the moment you create the array you tell the shape
c

array([[2, 1, 4],
       [6, 5, 6]])

In [79]:
b=np.array([[21,44,56],[54,34,67]]) #two dimentional array
b

array([[21, 44, 56],
       [54, 34, 67]])

In [80]:
b=np.array([[21,44,56],[54,34,67],[45,34,56]]) #two dimentional array
b

array([[21, 44, 56],
       [54, 34, 67],
       [45, 34, 56]])

In [81]:
np.zeros(10) # 0 elements 10

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [82]:
np.zeros((4,4)) # Row=4,Column=4  filled with 0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [83]:
np.zeros((2,3)) # Row=2,Column=3 filled with 0

array([[0., 0., 0.],
       [0., 0., 0.]])

In [84]:
np.ones(10)  # Array of 10 elements filled with 1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [85]:
np.ones(4) # Array of 4 elements filled with 1

array([1., 1., 1., 1.])

In [86]:
np.ones((3,2))   # Row=3,Column=2

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [87]:
np.ones((2,3))   # Row=2,Column=3

array([[1., 1., 1.],
       [1., 1., 1.]])