In [4]:
import numpy as np
a=np.array([[2,1,3],[4,5,7],[5,6,7]])
b=np.array([[6,2,8],[4,2,7],[1,5,8]])

In [5]:
a

array([[2, 1, 3],
       [4, 5, 7],
       [5, 6, 7]])

In [14]:
b

array([[6, 2, 8],
       [4, 2, 7],
       [1, 5, 8]])

In [14]:
b

array([[6, 2, 8],
       [4, 2, 7],
       [1, 5, 8]])

In [16]:
np.vstack((a,b))  # Vertically stack both a and b arrays, second array will be @ lower level

array([[2, 1, 3],
       [4, 5, 7],
       [5, 6, 7],
       [6, 2, 8],
       [4, 2, 7],
       [1, 5, 8]])

In [17]:
np.hstack((a,b)) # Horizontally stack both a and b arrays, second array will be @ Right Side

array([[2, 1, 3, 6, 2, 8],
       [4, 5, 7, 4, 2, 7],
       [5, 6, 7, 1, 5, 8]])

In [23]:
np.append(a,b,axis=0) # axis 0 means arrays are vertically aligned same as vstack

array([[2, 1, 3],
       [4, 5, 7],
       [5, 6, 7],
       [6, 2, 8],
       [4, 2, 7],
       [1, 5, 8]])

In [21]:
np.append(a,b,axis=1) # axis 1 means arrays are Horizontally aligned

array([[2, 1, 3, 6, 2, 8],
       [4, 5, 7, 4, 2, 7],
       [5, 6, 7, 1, 5, 8]])

In [29]:
np.concatenate((a,b),axis=0) # same as vertically aligned both arrays as vstack or or np.append>--axis 0

array([[2, 1, 3],
       [4, 5, 7],
       [5, 6, 7],
       [6, 2, 8],
       [4, 2, 7],
       [1, 5, 8]])

In [28]:
np.concatenate((a,b),axis=1) # same as Horizontally aligned both arrays as hstack or np.append>--axis 1

array([[2, 1, 3, 6, 2, 8],
       [4, 5, 7, 4, 2, 7],
       [5, 6, 7, 1, 5, 8]])

In [64]:
b=np.array([[5,1,6,5,4,6],[2,5,7,8,9,7],[3,4,6,7,8,9],[4,2,5,7,9,2]]) # 4 by 6 arry
b

array([[5, 1, 6, 5, 4, 6],
       [2, 5, 7, 8, 9, 7],
       [3, 4, 6, 7, 8, 9],
       [4, 2, 5, 7, 9, 2]])

In [70]:
np.hsplit(b,3) # break into 3 veritcal arrays by hsplit

[array([[5, 1],
        [2, 5],
        [3, 4],
        [4, 2]]),
 array([[6, 5],
        [7, 8],
        [6, 7],
        [5, 7]]),
 array([[4, 6],
        [9, 7],
        [8, 9],
        [9, 2]])]

In [71]:
np.vsplit(b,2) # break into 2 horizontal arrays by hsplit

[array([[5, 1, 6, 5, 4, 6],
        [2, 5, 7, 8, 9, 7]]),
 array([[3, 4, 6, 7, 8, 9],
        [4, 2, 5, 7, 9, 2]])]

In [43]:
np.hsplit(b,2) # break into 2 veritccal arrays by hsplit

[array([[5, 1, 6],
        [3, 5, 7],
        [3, 4, 6],
        [3, 2, 5],
        [0, 1, 2]]),
 array([[5, 4, 6],
        [8, 9, 7],
        [7, 8, 9],
        [7, 9, 2],
        [3, 5, 6]])]

In [47]:
h=np.array([2.32,1.24,3.21,6.35,7.78])
h

array([2.32, 1.24, 3.21, 6.35, 7.78])

In [49]:
h.astype(int)  # convert the entire arry to integer

array([2, 1, 3, 6, 7])

In [51]:
h.astype(str) # convert the entire arry to string

array(['2.32', '1.24', '3.21', '6.35', '7.78'], dtype='<U32')

In [72]:
import numpy as np
a=np.array([[2,1,3],[4,5,7],[5,6,7]])
b=np.array([[6,2,8],[4,2,7],[1,5,8]])

In [73]:
a+b

array([[ 8,  3, 11],
       [ 8,  7, 14],
       [ 6, 11, 15]])

In [75]:
a-b


array([[-4, -1, -5],
       [ 0,  3,  0],
       [ 4,  1, -1]])

In [77]:
10*a

array([[20, 10, 30],
       [40, 50, 70],
       [50, 60, 70]])

In [82]:
a*b #Hardamart product #this is element wise multiplication not matrice multiplication

array([[12,  2, 24],
       [16, 10, 49],
       [ 5, 30, 56]])

In [83]:
a.dot(b) #this is real matrice multiplication

array([[ 19,  21,  47],
       [ 51,  53, 123],
       [ 61,  57, 138]])

In [86]:
np.dot(a,b) #this is real matrice multiplication ...same as above

array([[ 19,  21,  47],
       [ 51,  53, 123],
       [ 61,  57, 138]])

In [84]:
b.dot(a) 

array([[60, 64, 88],
       [51, 56, 75],
       [62, 74, 94]])

In [85]:
np.dot(b,a)

array([[60, 64, 88],
       [51, 56, 75],
       [62, 74, 94]])

In [87]:
e=np.array([[1.23,3.45,5.67]])
[str(i) for i in e]

['[1.23 3.45 5.67]']

In [88]:
e=np.array([1.23,3.45,5.67])
[str(i) for i in e]

['1.23', '3.45', '5.67']