In [8]:
import numpy as np

In [111]:
np.random.randint(1,7) # gives an element with value  1 =<x <7

5

In [102]:
np.random.randint(1,7,10)

array([4, 4, 3, 4, 4, 5, 5, 4, 2, 2])

In [99]:
np.random.randint(1,7,5)

array([2, 3, 1, 1, 2])

In [100]:
np.random.randint(1,7,3)

array([4, 2, 5])

In [18]:
np.random.randint(1,7,(2,4))

array([[5, 2, 1, 6],
       [6, 1, 3, 2]])

In [19]:
np.random.randint(1,7,(5,7))

array([[1, 6, 5, 3, 4, 1, 2],
       [6, 2, 4, 5, 2, 2, 6],
       [1, 4, 6, 4, 4, 3, 4],
       [2, 5, 3, 3, 4, 5, 1],
       [1, 4, 5, 5, 2, 2, 6]])

In [24]:
np.random.random(5)  #gives 5 different decimals/float from 0 - 1

array([0.4462066 , 0.76139906, 0.02995654, 0.16826628, 0.77091907])

In [23]:
np.random.random((5,2))

array([[0.17032396, 0.12840752],
       [0.58624758, 0.61924049],
       [0.14043798, 0.09140799],
       [0.82353896, 0.87696843],
       [0.30952377, 0.79851729]])

In [27]:
np.random.random((5,4))  # 5 row 4 col decimals less than 1

array([[0.03795117, 0.19200452, 0.2202054 , 0.06329801],
       [0.66915958, 0.93816782, 0.57159455, 0.28833579],
       [0.70131645, 0.05519845, 0.26790147, 0.60955887],
       [0.60535831, 0.46984453, 0.1613901 , 0.97797167],
       [0.61965355, 0.4236447 , 0.37253218, 0.92686652]])

In [49]:
np.random.uniform(1,5)  # gives a decimal from 1> x <5  

2.059007350334727

In [61]:
np.random.uniform(6,12)  # gives a decimal from 6> x <12  

11.446530008038089

In [66]:
np.random.uniform(2,7,5) # gives a 5 element array with decimals starting from 2> x <7  

array([2.50249116, 5.23492151, 6.40344722, 4.46090307, 3.17561703])

In [67]:
np.random.uniform(3,9,(3,3)) # gives a 3 row by 3 col two dimentional array with elements having decimals starting from 3> x <9  

array([[7.70369684, 5.97210258, 5.90774089],
       [3.35414985, 7.23982186, 4.64692127],
       [6.33590373, 8.13342908, 4.30772621]])

In [70]:
np.random.uniform(3,9,(2,4)) # gives a 2 row by 4 col two dimentional array with elements having decimals starting from 3> x <9  

array([[8.7293385 , 5.78891673, 5.86244355, 6.12586195],
       [7.94506301, 8.58336156, 7.73538292, 5.52770737]])

In [124]:
x=np.random.uniform(3,9,(2,4)) # gives a 2 row by 4 col two dimentional array with elements having decimals starting from 3> x <9 
x

array([[7.81387469, 3.42703346, 5.61261522, 8.29758616],
       [5.14005469, 5.49424564, 3.31057249, 3.34608755]])

In [133]:
x.shape  # get the shape of the array

(4, 2)

In [132]:
x.shape=(4,2)   # change the shape of the array to 4 row 2 col
x

array([[7.81387469, 3.42703346],
       [5.61261522, 8.29758616],
       [5.14005469, 5.49424564],
       [3.31057249, 3.34608755]])

In [84]:
np.arange(10) # gives an array of 10 elements from 0 to 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
np.arange(15) # gives an array of 10 elements from 0 to 14

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [82]:
np.arange(3,15) # gives an array of elements starting from 3 to 15

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [81]:
np.arange(2,8) # gives an array of elements starting from 2 to 8

array([2, 3, 4, 5, 6, 7])

In [277]:
a=np.array([2,1,4,5,7,2,8,6,3,4,0,2])
a

array([2, 1, 4, 5, 7, 2, 8, 6, 3, 4, 0, 2])

In [278]:
a.shape

(12,)

In [279]:
a.shape=(3,4)  # 3X4 = 12 elements
a

array([[2, 1, 4, 5],
       [7, 2, 8, 6],
       [3, 4, 0, 2]])

In [280]:
a.shape=(2,6)  # 2X6 = 12 elements
a

array([[2, 1, 4, 5, 7, 2],
       [8, 6, 3, 4, 0, 2]])

In [138]:
b=np.array([2,1,4,5,6,8])
b

array([2, 1, 4, 5, 6, 8])

In [140]:
b=np.array([2,1,4,5,6,8]).reshape(2,3)  # re-shape the array at the moment of creation
b

array([[2, 1, 4],
       [5, 6, 8]])

In [141]:
a=np.array([2,1,4,5,6,8,3,4,5,6])
a

array([2, 1, 4, 5, 6, 8, 3, 4, 5, 6])

In [142]:
a[0]

2

In [143]:
a[6]

3

In [144]:
a[-1]

6

In [145]:
a[2:6]

array([4, 5, 6, 8])

In [207]:
b=np.array([[2,1,4,5,6,8,3,5],[3,5,4,5,6,1,3,5],[9,7,4,3,2,1,7,1],[2,1,4,5,7,5,1,3],[2,1,4,5,2,4,3,0]])
b

array([[2, 1, 4, 5, 6, 8, 3, 5],
       [3, 5, 4, 5, 6, 1, 3, 5],
       [9, 7, 4, 3, 2, 1, 7, 1],
       [2, 1, 4, 5, 7, 5, 1, 3],
       [2, 1, 4, 5, 2, 4, 3, 0]])

In [208]:
b[0,0] # element in tow 0 , col 0   i.e ---->2

2

In [209]:
b[1,1]   # element in row 1 , col 1   i.e ---->5

5

In [210]:
b[2,0]   # I want to get value 9  < ---row 2 col 0

9

In [211]:
b[3,4]  # element in row 3 , col 4   i.e ---->7

7

In [218]:
b

array([[2, 1, 4, 5, 6, 8, 3, 5],
       [3, 5, 4, 5, 6, 1, 3, 5],
       [9, 7, 4, 3, 2, 1, 7, 1],
       [2, 1, 4, 5, 7, 5, 1, 3],
       [2, 1, 4, 5, 2, 4, 3, 0]])

In [244]:
b[0:3,0:4]  # ( start row: end row , col start: col end)  #Row 0  row 3  , col 0  col4  

array([[2, 1, 4, 5],
       [3, 5, 4, 5],
       [9, 7, 4, 3]])

In [222]:
b[1:4,1:5]

array([[5, 4, 5, 6],
       [7, 4, 3, 2],
       [1, 4, 5, 7]])

In [163]:
b[3:4,2:5]

array([[4, 5, 3]])

In [179]:
b[:4,2:]

array([[4, 5, 6, 8, 3, 5],
       [4, 5, 6, 1, 3, 5],
       [4, 3, 2, 1, 7, 1],
       [4, 5, 7, 5, 1, 3]])

# How to perform mathamatical operations with arrays

In [180]:
import numpy as np

In [187]:
a=np.array([2,1,3,5])
b=np.array([6,2,7,8])

In [188]:
a*10   # element wise operation is happened here in numpy arrays Lists

array([20, 10, 30, 50])

In [189]:
a+5

array([ 7,  6,  8, 10])

In [190]:
a+b

array([ 8,  3, 10, 13])

In [192]:
a/b   # every element in array a is divided by coresponding element of array b

array([0.33333333, 0.5       , 0.42857143, 0.625     ])

In [194]:
p=np.array([[2,1,3],[3,4,2]])
k=np.array([[6,2,8],[2,6,4]])

In [195]:
p

array([[2, 1, 3],
       [3, 4, 2]])

In [196]:
k

array([[6, 2, 8],
       [2, 6, 4]])

In [197]:
p+k

array([[ 8,  3, 11],
       [ 5, 10,  6]])

In [198]:
p-k

array([[-4, -1, -5],
       [ 1, -2, -2]])

In [199]:
p*k

array([[12,  2, 24],
       [ 6, 24,  8]])

In [200]:
p/k

array([[0.33333333, 0.5       , 0.375     ],
       [1.5       , 0.66666667, 0.5       ]])

In [201]:
a=np.array([2,1,3,5,3,5,6,7])

In [203]:
a>5  # element wise relational operation

array([False, False, False, False, False, False,  True,  True])

In [205]:
a>=5  # element wise relational operation

array([False, False, False,  True, False,  True,  True,  True])

In [265]:
a[0]=10  # numpy arrays are always mutable
a

array([10,  1,  3,  5,  4])

In [281]:
a=np.array([2,1,3,5,4]) # declare 5 element array

In [282]:
a.shape # see how many elements

(5,)

In [283]:
a[[True,True,False,False,True]] # gives only the elements satisfying the condition True

array([2, 1, 4])

In [284]:
a[a>=2]  # gives only the elements satisfying the condition >=2

array([2, 3, 5, 4])

In [285]:
a[a%2==0]  # gives only the elements satisfying the condition i.e even numbers here

array([2, 4])

In [286]:
a[a%2!=0]  # gives only the elements satisfying the condition i.e odd numbers here

array([1, 3, 5])

In [287]:
a

array([2, 1, 3, 5, 4])

In [288]:
a[a+2<=6]

array([2, 1, 3, 4])

# Statistical summeries for array function

In [289]:
import numpy as np

In [309]:
a=np.array([2,1,3,5,4,6,7,8,9,0]) # declare 5 element array

In [310]:
a.shape

(10,)

In [311]:
a.sum()

45

In [312]:
#or
np.sum(a)

45

In [313]:
a.mean()

4.5

In [314]:
np.mean(a)

4.5

In [315]:
a.max()

9

In [316]:
np.max(a)

9

In [317]:
np.min(a)

0

In [318]:
a.min()

0

In [319]:
a.var()

8.25

In [320]:
np.var(a)

8.25

In [321]:
a.std()

2.8722813232690143

In [322]:
np.std(a)

2.8722813232690143

In [323]:
np.median(a)

4.5

In [324]:
a.median() # median not works this way

AttributeError: 'numpy.ndarray' object has no attribute 'median'