In built python base functions

In [1]:
L=[1,2,4,5,6,8]

In [2]:
len(L)

6

In [3]:
L.append(10)

In [4]:
L

[1, 2, 4, 5, 6, 8, 10]

# Modules/Libraries   
Modules/Libraries <---Collectin of several related Calsses and function or A set of tools to perform special set of tasks

A Package <--- is a collection of Modules (A huge collection of function and modules)

We first need to import them to work with them

import random<BR>
import numpy<BR>
import matplotlib<BR>
import pandas<BR>
import seaborn


In [38]:
# work with random maths module
import random
random.randrange(1,10) # This does not include the upper most value
# i,e here 10 will never be generated

3

In [39]:
random.randrange(1,50)

10

In [24]:
random.randrange(0,10)

9

In [32]:
random.randrange(10) # This is equal to random.randrange(0,10) but does not include last val

4

In [37]:
random.randint(1,5)# Thsi include the uppervalue as well  i.e print 5 also

5

In [43]:
random.random() # Generate random number from 0 to 1

0.733812271825348

In [61]:
random.uniform(0,1) # Generate random decimal  number from 0 to 1

0.1495947327155105

In [62]:
random.uniform(2,6)  # Generate random decimal  number from 2 to 6

5.6984293580848195

In [63]:
import random

In [64]:
L=[10,20,30,40,50,60,70]
T=(2,4,3,5,6,8,8,9,0,0,3,2,1)
S="Today is a very beautiful day"

In [65]:
random.choice(L) # to get an element from a list/tuple/string


10

In [66]:
random.choice(T)

4

In [67]:
random.choice(S)

'f'

In [72]:
random.sample(L,4) #provide you 4 random samples from the List L

[50, 30, 60, 20]

In [73]:
random.sample(T,5) #provide you 5 random samples from the Tuple T

[6, 9, 0, 2, 1]

In [75]:
random.sample(S,3) #provide you 3 random samples from the Stgrng S

['u', ' ', 'e']

In [78]:
import random
L=[23,34,56,78,97]
random.shuffle(L)
L

[23, 97, 78, 56, 34]

In [79]:
import numpy

In [84]:
numpy.array([2,1,3,4]) # we have to give the numpy all the time
                       # we can use an alias or nick name

array([2, 1, 3, 4])

In [87]:
import numpy as x  # we can use an alias 

In [86]:
x.array([2,1,3,4])

array([2, 1, 3, 4])

In [100]:
import numpy as np  # we can use meaningful alias as agreed by coders 
import pandas as pd
import seaborn as sns
import numpy.linalg as lg  # You can directly import only the sub library in sie numpy
import matplotlib.pyplot as plt  # You can directly import only plotting module of matplotlib
#for huge libraries we only import the required fub module with "from"
#import sklearn   <--- dont import this way for bigger modules
from sklearn.model_selection import train_test_split,cross_val_score
from numpy import linalg as lig

In [90]:
np.array([2,1,3,4])

array([2, 1, 3, 4])

In [91]:
np.linalg.inv()  # accessing linear algebra library in numpy

TypeError: _unary_dispatcher() missing 1 required positional argument: 'a'

In [92]:
np.random.uniform()

0.08582653751467662

# Exception Handling

In [103]:
print 10+20  #sample SyntaxError

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (3758121376.py, line 1)

In [108]:
x=10
if x>=20              
    print("Yes") #sample SyntaxError  for no ":" for if   

SyntaxError: expected ':' (2689691699.py, line 2)

In [113]:
L=[1,23,45,54,'Sam]

SyntaxError: unterminated string literal (detected at line 1) (2242119391.py, line 1)

In [116]:
10+"100"  # <----Data types does not match int+String

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [119]:
import numpi  # <  we try to import unknown module due to typo

ModuleNotFoundError: No module named 'numpi'

In [122]:
print(t)  #<---Name error given for still not defined variables

NameError: name 't' is not defined

In [125]:
L=[2,1,3,5,5]  #ValueError given for value not in this list
L.remove(9)
L

ValueError: list.remove(x): x not in list

In [126]:
d={"a":10,"b":20,"c":40}

In [128]:
d["a"]

10

In [131]:
d["g"]  #<--- keyError for undefined keys

KeyError: 'g'

In [134]:
L=[3,2,5,6,8]   #<--- 9 no in this list, thus no matching index
L[9]

IndexError: list index out of range

In [136]:
10/0  #<---ZeroDivisionError                         

ZeroDivisionError: division by zero

In [137]:
#we can create our own exceptions with raise or asertion

In [141]:
x=30
if x<=20:
    raise Exception("Value not in right region")
print(x*2)

60


In [143]:
x=10
if x<=20:
    raise Exception("Value not in right region") # Our error
print(x*2)

Exception: Value not in right region

In [156]:
L=[12,13,23,34,45,46]
x=13
if x%2==0:   #<-- if condition not met Error not thrown
    raise Exception("You cannot remove an even value")
L.remove(x)
print(L)

[12, 23, 34, 45, 46]


In [155]:
L=[12,13,23,34,45,46]
x=12
if x%2==0:  #<-- if condition met Error thrown
    raise Exception("You cannot remove an even value")
L.remove(x)
print(L)

Exception: You cannot remove an even value

In [151]:
x=30
assert x>20, "Value is not in the correct region"
print(x*2)

60


In [157]:
#assert
x=10
assert x>20, "Value is not in the correct region"  #<-- if condition not met Error thrown
print(x*2)

AssertionError: Value is not in the correct region